### ISSUE TITLE
don't fetch entire git source

### ISSUE THREAD

**Issue by mralusw** [TuxInvader/focal-mainline-builder#1]
Is it possible to check out just the specific version being built instead of the entire `cod` tree? I see that `build.sh` has an option to skip the update step, but after building it still does `git checkout master`.

Consider using `git switch $kver` instead of `git checkout`. At the end you can do `git switch` (without arguments) to switch back to the previous state of the local git repo (if that is important).

It's also possible to use git worktrees (`git worktree add /new/path <commit-ish>`) to checkout the desired revision somewhere in `tmp` and leave the main local repo alone. At the end you can simply drop the temporary worktree, and not worry about cleanup at all.

**Comment by TuxInvader** [comment]
I was not aware of `git worktree` (thanks for educating me), it sounds like it would be perfect, except I just tested it and the worktree for `cod/mainline/v5.12.2` and the temp folder is 1.2G! So maybe sticking with the mounted volume and the provided tree would be best.

I also tried out `git switch` (again I was unaware of this command, thanks) but it seems like it only works with branches, and the mainline kernel releases are all tags. I suppose I could checkout the tag into a local branch, but then do I delete it again afterwards??? 

I'll take your advice on limiting the pulls and checkouts to just the versions requested by the user. ie: stop pulling master, limit the  update part to just `git fetch --tags origin`, and then `git checkout cod/mainline/$kver` prior to the build. Cleanups I'll do in the current `cod/mainline/$kver` tree too.

I guess an example use-case here is someone who only wants to build a specific 5.12 kernel. So they could clone with:
```
git clone --depth 1 -b cod/mainline/v5.12.2 \
    git://git.launchpad.net/~ubuntu-kernel-test/ubuntu/+source/linux/+git/mainline-crack /usr/local/src/cod/mainline
``` 

And then build just that package:
```
docker run -ti -e kver=v5.12.2 -v /usr/local/src/cod/mainline:/home/source \
     -v /usr/local/src/cod/debs:/home/debs --rm tuxinvader/focal-mainline-builder:latest --update=no
```

The script will then run the clean and reset, followed by a checkout of "cod/mainline/v5.12.2", do the build, and finally another clean and reset. It won't update any tags or pull master. 

See https://github.com/TuxInvader/focal-mainline-builder/commit/cf374e49f60f783879df3f3dc612e422e1c59646

**Comment by mralusw** [comment]
I haven't tested your latest, but it sounds good.

Regarding `git switch`, to correct myself:
- `git switch -` (with a dash) is the command to switch to the previous state
- you can use `git switch --detach <commit-ish>` to switch to non-branches (in case you ever need it). Obviously this yields a detached-HEAD state

**Comment by TuxInvader** [comment]
I'm confident that we no longer pull any more data from git than is required for the specific build, so closing this. 
Thanks!

**Comment by mralusw** [comment]
The cloning / docker commands for sticking to a single series (e.g. 5.10) would be a nice addition to the docs.

I see that there is now also a switch to apply patches to the kernel tree; presumably one would check out plain 5.10 and then request --patch=5.10.X, increasing X repeatedly?

**Comment by TuxInvader** [comment]
I'll update the docs later... 

wrt --patch, it downloads the patch release file from kernel.org, so you can only bump one version. Eg 5.11.19 to 5.11.20. I've tested it and it doesn't build, I'm not sure why. The patch applied (some were skipped due to already being in the ubuntu version) but It failed to build somewhere in the nouveau module.

I also noticed the mainline build generates some ABI files in debian.master, and I'm not sure where they come from, so even if the build had worked I could well have failed at the package building step.
