### ISSUE TITLE
No boot since 5.14.11

### ISSUE THREAD

**Issue by ThoreauHenry** [TuxInvader/focal-mainline-builder#11]
Hello there.

I just wanted to let you know that there seems to be a boot error on 20.04 with kernels 5.14.12 and up.  I don't know what the ubuntu people changed, but it seems to be the same issue as before when you recompiled their kernel.  It looks like it's loading up drivers, network, but the video never loads.  Like the video driver is wrong or it's hung up on that kernel switch that the ubuntu developers are using.  I forget the name usbmon_blah_blah something.  Whatever it was they did to jack up the kernel for LTS, it looks like it's back.  Could you test on some non-virtual hardware if possible.  This device with this issue is a old intel laptop.  So, the drivers are fairly mature.  Specs are listed below:

System:    Host: user Kernel: 5.14.11-051411-generic x86_64 bits: 64 Desktop: Cinnamon 5.0.6 Distro: Linux Mint 20.2 Uma 
Machine:   Type: Laptop System: Dell product: Latitude E6420 v: 01 serial: CptCrunch 
           Mobo: Dell model: 0K0DNP v: A01 serial: gerbil BIOS: Dell v: A26 date: 09/14/2018 
Battery:   ID-1: BAT0 charge: 93.7 Wh condition: 93.7/96.6 Wh (97%) 
CPU:       Topology: Quad Core model: Intel Core i7-2760QM bits: 64 type: MT MCP L2 cache: 6144 KiB 
           Speed: 807 MHz min/max: 800/3500 MHz Core speeds (MHz): 1: 885 2: 949 3: 820 4: 833 5: 819 6: 846 7: 898 
           8: 898 
Graphics:  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics driver: i915 v: kernel 
           Display: server: X.Org 1.20.11 driver: modesetting unloaded: fbdev,vesa resolution: 1366x768~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 3000 (SNB GT2) v: 3.3 Mesa 21.2.4 - kisak-mesa PPA 
Audio:     Device-1: Intel 6 Series/C200 Series Family High Definition Audio driver: snd_hda_intel 
           Sound Server: ALSA v: k5.14.11-051411-generic 
Network:   Device-1: Intel Wi-Fi 6 AX200 driver: iwlwifi 
           IF: wlp2s0 state: up mac: an:dc:he:es:ee 
Drives:    Local Storage: total: 465.76 GiB used: 271.44 GiB (58.3%) 
           ID-1: /dev/sda vendor: Samsung model: SSD 860 EVO 500GB size: 465.76 GiB 
Partition: ID-1: / size: 338.74 GiB used: 271.44 GiB (80.1%) fs: ext4 dev: /dev/sda3 
Sensors:   System Temperatures: cpu: 52.0 C mobo: 27.0 C sodimm: 36.0 C 
           Fan Speeds (RPM): cpu: 0 
Info:      Processes: 300 Uptime: 19m Memory: 7.65 GiB used: 2.08 GiB (27.2%) Shell: bash inxi: 3.0.38

There are no fatal hardware errors in dmesg.  Software packaging is clean.

Thank you for your time.  Your kernel has made Ubuntu LTS suck a lot less.

**Comment by TuxInvader** [comment]
Hi Henry....

Are you saying that the laptop starts up okay, and everything is working except for the desktop? Do you have a console login screen, or is it just blank? If it's blank does `ctrl + alt + F1` get you to a console login?

What output do you have from `lspci -vv`

**Comment by TuxInvader** [comment]
See: https://gitlab.freedesktop.org/drm/intel/-/issues/4297

**Comment by ThoreauHenry** [comment]
> See: https://gitlab.freedesktop.org/drm/intel/-/issues/4297

Yes, this is the exact issue.  Dead boot.  No screens.  No display past grub kernel load.
It looks like it was updated 3 days ago.  Kernel released yesterday..  Hmm..

https://gitlab.freedesktop.org/drm/nouveau/-/commit/6e6f96630805874fa80b0067e1a57aafc06225f6

I'll do a test run on 5.15 with git /lib/firmware and see where it's at.  Thanks for tracking down the issue, even though it's not in your wheelhouse.

What you asked for previously: 

https://pastebin.com/gVgsnW0n

**Comment by ThoreauHenry** [comment]
OK, I'm back and running.  Seems to have been resolved with 5.15 and git firmware.

$ uname -a
Linux user 5.15.0-051500-generic #202110312130 SMP Sun Oct 31 21:33:20 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

git clone git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git

Errors:
$ sudo dmesg | grep -i error
[sudo] password for user:     
[    0.187409] acpi PNP0A08:00: _OSC: platform retains control of PCIe features (AE_ERROR)
[    0.476962] RAS: Correctable Errors collector initialized.
[    3.694509] EXT4-fs (sda3): re-mounted. Opts: errors=remount-ro. Quota mode: none.
[    4.237368] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
[    4.288403] iwlwifi 0000:02:00.0: Direct firmware load for iwlwifi-cc-a0-66.ucode failed with error -2
[    4.288434] iwlwifi 0000:02:00.0: Direct firmware load for iwlwifi-cc-a0-65.ucode failed with error -2
[    4.288458] iwlwifi 0000:02:00.0: Direct firmware load for iwlwifi-cc-a0-64.ucode failed with error -2

The kernel people haven't seemed to want to release AX200/wifi 6 firmware properly, so those are the only errors I get ATM.  And I can see my display, which is very useful.  Thank you for all of your help Mark.  I appreciate it.  I'm going to closed this issue as resolved.
