### ISSUE TITLE
Add 5.15 to long-term ppa 

### ISSUE THREAD

**Issue by m1khal3v** [TuxInvader/focal-mainline-builder#12]
At the moment, the long-term ppa only contains the 5.10 branch, but 5.15 is now also a lts version. Please add build of 5.15 branch to the long-term ppa, it is very convenient to use

**Comment by m1khal3v** [comment]
I had to figure out how ppa work. If someone needs it, I will upload the 5.15 branch here https://launchpad.net/~m1khal3v/+archive/ubuntu/5.15-focal

**Comment by TuxInvader** [comment]
I have also added 5.15 to my longterm ppa. Thanks @m1khal3v
