### ISSUE TITLE
Info request: Origin of kernel source used

### ISSUE THREAD

**Issue by heurekus** [TuxInvader/focal-mainline-builder#13]
Hi, very cool project, thanks very much! Could you give more info how the kernel sources you use get into 

git://git.launchpad.net/~ubuntu-kernel-test/ubuntu/+source/linux/+git/mainline-crack

and what modifications are done. Are you the owner of that repository?

Cheers,
Martin

**Comment by TuxInvader** [comment]
Hi Martin,

That repository is owned and managed by the Ubuntu mainline kernel team. It's the tree they use to build mainline/test kernels which eventually make it into an Ubuntu release.

All I do is pull the latest version and build into a package using the LTS toolchain.

Cheers,
Mark

**Comment by heurekus** [comment]
I Mark,

thanks for the feedback, I found the way to the ownership declaration now. https://code.launchpad.net/~ubuntu-kernel-test/ubuntu/+source/linux/+git/mainline-crack

I'm considering running your container setup here to compile the latest kernel myself, as Ubuntu LTS has switched to 5.13, which unfortunately breaks AMD Ryzen 4xxx suspend/resume. That's fixed again in 5.15. I don't expect Canonical to patch it back and just let me wait till April when they go for 5.15 on 20.04 LTS anyway. I could still be surprised, but I don't expect it :)

Many thanks, this is cool!
-Martin
