### ISSUE TITLE
"kernel version you specified is not installed" when trying install an module in updated initrd 5.17

### ISSUE THREAD

**Issue by Augusto7743** [TuxInvader/focal-mainline-builder#17]
Hello.
I have installed Ubuntu 20.04.3 kernel 5.11.
After installed PPA https://launchpad.net/~tuxinvader/+archive/ubuntu/lts-mainline
sudo apt-get install linux-generic-5.17

Using uname -r show
5.17.3-051703-generic

Using dpkg --list | grep linux-image
ii  linux-image-5.11.0-27-generic                 5.11.0-27.29~20.04.1                amd64        Signed kernel image generic
ii  linux-image-generic-hwe-20.04                 5.11.0.27.29~20.04.11               amd64        Generic Linux kernel image
ii  linux-image-unsigned-5.17.3-051703-generic    5.17.3-051703.202204140912          amd64        Linux kernel image for version 5.17.3 on 64 bit x86 SMP

I have installed Rapiddisk (disk read write cache utility).
Rapiddisk have option to install modules in initrd with an command line

sudo bash install_initrd.sh --install --size=128 --cache-mode=wb --kernel=5.11.0-27-generic

changing 5.11.0-27-generic to 5.17.3-051703-generic show the message
**** Error: the kernel version you specified is not installed. Exiting...

I have installed the files below from PPA
linux-headers-5.17.3-051703_5.17.3-051703.202204140912_all
linux-headers-5.17.3-051703-generic_5.17.3-051703.202204140912_amd64.deb
linux-generic-5.17_5.17.3_amd64
linux-image-unsigned-5.17.3-051703-generic_5.17.3-051703.202204140912_amd64
linux-modules-5.17.3-051703-generic_5.17.3-051703.202204140912_amd64

I not understand if need any another file to register information in OS allowing the command line work with the updated kernel.
Please is need to install more others files ? Is correct install kernel 5.17 directly over 5.11 not installing kernel 5.13 before ?

Thanks for read.
Have an nice week.

**Comment by TuxInvader** [comment]
Please modify your `install_initrd.sh` script and change line 178

```diff
-       kernel_installed="$(dpkg-query --list | grep -P 'linux-image-\d' |grep '^.i'| awk '{ print $2 }'| sed 's,linux-image-,,')"
+       kernel_installed="$(dpkg-query --list | grep -P 'linux-image-(unsigned-)?\d' |grep '^.i'| awk '{ print $2 }'| sed -re 's,linux-image-(unsigned-)?,,')"
```

Currently the script does not support unsigned kernels, this change will make it detect both signed and unsigned. 
If this works for you then you might want to request a change on the pkoutoupis/rapiddisk project.

**Comment by Augusto7743** [comment]
Now the script works.
Thanks very much for your reply.
Have an nice week and again thanks for your PPA.

**Comment by TuxInvader** [comment]
I'm glad it's working. Closing this issue :-)
