### ISSUE TITLE
debug info package needed

### ISSUE THREAD

**Issue by vibrys** [TuxInvader/focal-mainline-builder#19]
It's quite a big package and I understand that is quite troublesome to have such large blob ready to download, but I don't see any option to build one from local docker.
What way do you suggest then? (IMO: still the best would be to provide option to docker)

**Comment by TuxInvader** [comment]
Hi @vibrys 

I've just added an option to support building the dbgsyms packages (4d29ac81814a55483f05b536d94ac84840078829). Add `--debug=yes` to your binary build in docker. Eg: 

```
docker run -ti -e kver=v5.18.3 -v /usr/local/src/cod/mainline:/home/source \
-v /usr/local/src/cod/debs:/home/debs --rm tuxinvader/focal-mainline-builder:latest \
--rename=yes --buildmeta=yes --flavour=generic --checkbugs=yes --update=yes --btype=binary --debug=yes
```

**Comment by vibrys** [comment]
wow!! thank You for prompt action. I'm trying this new feature on v5.12. I'll let You know when I'm done. best regards!

**Comment by vibrys** [comment]
works great! thank You!!
