### ISSUE TITLE
Ubuntu 22.04 Support

### ISSUE THREAD

**Issue by Theelx** [TuxInvader/focal-mainline-builder#21]
Is it reasonable to expect your PPA to eventually support the latest kernels for 22.04, or would we need to fork this and make that change ourselves? I love the ease with which you've made the latest Linux kernels accessible to Ubuntu users, and I hope that eventually we'll get to enjoy these amazing kernels on 22.04!

**Comment by Augusto7743** [comment]
Bionic 18.04 too ? kernel there is very old, but is the last Ubuntu for 32 bits cpus.

**Comment by TuxInvader** [comment]
maybe.... I really need to automate the build, upload and deletion. At the moment I manage it manually, and while it only takes a few minutes to build a source package it's not something I'm going to expand. If/When I automate the process, then maybe :-)

**Comment by Theelx** [comment]
Can you detail the steps you use to make the build? I'd like to try to automate it.

**Comment by TuxInvader** [comment]
I would use Ansible to perform the following tasks:  

- Check for new kernel tag in Git
- Use the Launchpad API to check for space in PPA, and remove oldest image if required
- run the docker build
- upload the source package with dput
- Monitor build and report on errors

Cheers

**Comment by Theelx** [comment]
I've gotten the first step down, but I'm having trouble using launchpadlib to check the free space in the PPA. I can't find any examples online, the documentation isn't clear, and I can't find any mention of such an API endpoint in the source code. Do you have any idea how to do it?

**Comment by username227** [comment]
I add a +1 to this. I just upgraded to Mint 21, and I REALLY, REALLY miss your PPA. Hoping you'll support jammy soon!

**Comment by Theelx** [comment]
I've been making some progress on automating it with Ansible, and I'd like to propose that I maintain a separate PPA for Jammy, partly so that the 2GB limit on PPA size doesn't mean focal support has to be dropped from the current one.

**Comment by username227** [comment]
> I've been making some progress on automating it with Ansible, and I'd like to propose that I maintain a separate PPA for Jammy, partly so that the 2GB limit on PPA size doesn't mean focal support has to be dropped from the current one.

That's fine with me, of course. Once this is figured out, if you would simply update this thread so people will be aware, I would greatly apprecicate it. Thank you both very much for all your work on this.

**Comment by muzena** [comment]
I made for [jammy kernel](https://launchpad.net/~trebelnik-stefina/+archive/ubuntu/kernel/+packages) PPA
I will try to make auto builds using PPA recepies.
@TuxInvader 
Can you check **lowlatency** kernel build, I tried to build source and upload to ppa but it builds debian and kernel tar source archives with a few bytes.

**Comment by username227** [comment]
> I made for [jammy kernel](https://launchpad.net/~trebelnik-stefina/+archive/ubuntu/kernel/+packages) PPA I will try to make auto builds using PPA recepies. @TuxInvader Can you check **lowlatency** kernel build, I tried to build source and upload to ppa but it builds debian and kernel tar source archives with a few bytes.

Nice work. Thanks. Appears to work like a charm with Mint 21.

**Comment by TuxInvader** [comment]
Cool. Great job @muzena. Did either you or @Theelx make any progress with automation? 
I must admit I haven't looked any further into it myself.

**Comment by TuxInvader** [comment]
@muzena - Can you check you're using the latest version of the container please? There was an issue with lowlatency which was fixed already in #16

**Comment by muzena** [comment]
@TuxInvader 
I think so, how can I check this?
I use command:
sudo docker run -ti -e kver=v5.19 -v $HOME/cod/mainline:/home/source \
     -v $HOME/cod/debs:/home/debs -v ~/.gnupg:/root/keys \
     --rm tuxinvader/focal-mainline-builder:latest \
     --btype=source \
     --flavour=lowlatency \
     --exclude=udebs \
     --sign=04F57DA7D5E421C8F465571373D22AAAAAAAC235 \
     --rename=yes \
     --buildmeta=yes \
     --maintainer="Name <mail@gmail.com>" \
     --series=jammy \
     --rename=yes \
     --update=no

I can post build log if necessary.
And another error is debsign failed only for lowlatency source.

**Comment by TuxInvader** [comment]
It should have the below image_id and be the same as tag 1.5
```
$ docker images
REPOSITORY                          TAG             IMAGE ID       CREATED         SIZE
tuxinvader/focal-mainline-builder   latest          cb38eebf64c3   10 days ago     605MB
tuxinvader/focal-mainline-builder   v1.5            cb38eebf64c3   10 days ago     605MB
```
pulling it again should update it if necessary: `docker pull tuxinvader/focal-mainline-builder:latest`

**Comment by muzena** [comment]
$ sudo docker images
REPOSITORY                          TAG       IMAGE ID       CREATED       SIZE
tuxinvader/focal-mainline-builder   latest    cb38eebf64c3   11 days ago   605MB

$ sudo docker pull tuxinvader/focal-mainline-builder:latest
latest: Pulling from tuxinvader/focal-mainline-builder
Digest: sha256:8a3d83d2bfca50c9e9185314ccc4c73bd46b5a5419d229e90315826a27cb42bd
Status: Image is up to date for tuxinvader/focal-mainline-builder:latest
docker.io/tuxinvader/focal-mainline-builder:latest

**Comment by TuxInvader** [comment]
please post your build log

**Comment by Theelx** [comment]
I've been busy the past few days so I haven't had a chance to post my work so far or monitor this thread that much. However, as for automation, I managed to make some scripts for checking the used space of built packages, checking the most recent tags on mainline crack and building the kernel with that, however I am stuck on how to upload the packages with dput automatically. Also I haven't bothered to sign the packages with a GPG key yet but that's on my list.

I'll try to post a gist later today (EST) with my ansible script so far, plus the accompanying helper scripts.

**Comment by TuxInvader** [comment]
@muzena - I've just added a jammy branch for building jammy on jammy. It also undoes a GCC tweak needed for building recent kernels on focal. Can you try pulling the image `tuxinvader/jammy-mainline-builder:latest`, and building with that?

How long did it take to barf on your attempt? I currently have a test build running here: https://launchpad.net/~tuxinvader/+archive/ubuntu/kernel-build-tools/+build/24269518

**Comment by muzena** [comment]
@TuxInvader 
Same thing with lowlatency kernel.
Can you try upload source for [lowlatency kernel](https://launchpad.net/~trebelnik-stefina/+archive/ubuntu/multisystem/+packages?field.name_filter=&field.status_filter=published&field.series_filter=jammy)?
I will try tomorrow, today Launchapd is falling apart, I get error, errror., error... on loading Launchpad web site.

**Comment by TuxInvader** [comment]
It worked for me? I uploaded a source package built with jammy-mainline-builder and flavour lowlatency as a test here: https://launchpad.net/~tuxinvader/+archive/ubuntu/kernel-build-tools/+packages

5.19.1 built successfully.

**Comment by username227** [comment]
Any movement on this? Would love to see a PPA for jammy that works like this one. thanks!

**Comment by masemoel** [comment]
masemoel@HPPavilion15-EC2014NS:~$ sudo add-apt-repository ppa:tuxinvader/lts-mainline -y
[sudo] password for masemoel:     
Cannot add the PPA: «'This PPA doesn't support jammy'».

Any news for this?

**Comment by username227** [comment]
> masemoel@HPPavilion15-EC2014NS:~$ sudo add-apt-repository ppa:tuxinvader/lts-mainline -y [sudo] password for masemoel: Cannot add the PPA: «'This PPA doesn't support jammy'».
> 
> Any news for this?

Try this PPA. It does not work quite like tuxinvader. It does update the kernel, and he does seem to be having some luck with building kernels even when ubuntu mainline fails. But in mintupdate, it doesn't yet identify his kernels as updates to the linux kernel. It is promising though and worth subscribing to.

https://launchpad.net/~trebelnik-stefina/+archive/ubuntu/kernel

**Comment by muzena** [comment]
@TuxInvader 
This option;
> Falvour: You can pass --flavour=[generic|lowlatency] if you want to limit the build to just one flavour. Default is none, and we build both.


> Default` is none, and we build both.

Default it builds only generic kernel and not both, generic and lowlatency kernels.

**Comment by TuxInvader** [comment]
We're getting closer. I've started working on ansible automation for pruning old packages and uploading new.
I almost have all the bits to make these PPAs look after themselves :-)

See: https://github.com/TuxInvader/ansible_collection_tuxinvader_launchpad

**Comment by TuxInvader** [comment]
> @TuxInvader This option;
> 
> > Falvour: You can pass --flavour=[generic|lowlatency] if you want to limit the build to just one flavour. Default is none, and we build both.
> 
> > Default` is none, and we build both.
> 
> Default it builds only generic kernel and not both, generic and lowlatency kernels.

I think this changed when the lowlatency kernel stopped being a flavour. I need to update the docs.

**Comment by muzena** [comment]
@TuxInvader 
Is it possible to adjust kernel versioning, to be able automatically upgraded:
eg. 5.19.9 to 5.19.10 -> 5.19.11 -> 5.19.12 ..., instead manually installation on every new release of kernel ?

**Comment by TuxInvader** [comment]
@muzena install the `linux-generic-5.19` package. It's a meta-package that always depends on the latest minor release. As long as you have that, then apt will upgrade to the latest release during a normal `apt update`.

**Comment by TuxInvader** [comment]
In more on-topic news.... I've created https://launchpad.net/~tuxinvader/+archive/ubuntu/jammy-mainline - which will soon start receiving automated kernel builds from mainline/stable. Ansible is creating a source package as I type.

**Comment by masemoel** [comment]
I confirm that the new ppa for jammy works fine :)
I have used Linux Mint 21 in my case but should work for Ubuntu 22 and other derivates I guess...

```
sudo add-apt-repository ppa:tuxinvader/jammy-mainline
sudo apt update
sudo apt install linux-generic-5.19
```

Rebooted and neofetch showing 5.19.11-generic kernel.

Many thanks!

**Comment by username227** [comment]
Unless i'm missing something, your automated process didn't seem to build kernel 6.0 in the new jammy repository. Is there an issue with this?

**Comment by TuxInvader** [comment]
Yeah - the initial release of any new kernel is into `mainline`, the automation scripts were checking `stable`. I fixed this last night, but left it to this mornings automated job to actually publish it. It's up there now.

**Comment by TuxInvader** [comment]
Closing this issue as https://launchpad.net/~tuxinvader/+archive/ubuntu/jammy-mainline is now hosting kernels for 22.04

**Comment by muzena** [comment]
@TuxInvader 
Can you enable other CPU architectures and add lowlatency kernel in PPA?
I think it's better to acitave/make a TuxInvader team in launchpad, then you can make PPA in team and upload/store more then 2GB in PPA.
Eg. like this team PPA:
https://launchpad.net/~devilutionx
https://launchpad.net/~devilutionx/+archive/ubuntu/dev/+packages

Repository size:
    6.8 GiB (100.00%) of 4.0 GiB

**Comment by username227** [comment]
> @TuxInvader Can you enable other CPU architectures and add lowlatency kernel in PPA? I think it's better to acitave/make a TuxInvader team in launchpad, then you can make PPA in team and upload/store more then 2GB in PPA. Eg. like this team PPA: https://launchpad.net/~devilutionx https://launchpad.net/~devilutionx/+archive/ubuntu/dev/+packages
> 
> Repository size: 6.8 GiB (100.00%) of 4.0 GiB

Correct me if i'm wrong, but didn't Ubuntu do away with lowlatency kernel?
