### ISSUE TITLE
focal-mainline-builder fixdep and gcc not foound errors in docker run

### ISSUE THREAD

**Issue by dbergstein** [TuxInvader/focal-mainline-builder#24]
I was trying to build kernel 5.18.15 and ran into the errors below.  This was for the following command line:

sudo docker run -ti -e kver=v5.18.15 -v /usr/local/src/cod/mainline:/home/source -v /usr/local/src/cod/debs:/home/debs --rm tuxinvader/focal-mainline-builder:latest

Excerpt from output:
[ "false" != 'true' ] && true || \
        rsync -a --exclude debian --exclude debian.master --exclude debian.master * /home/source/debian/build/build-generic
cat /home/source/debian.master/config/config.common.ubuntu /home/source/debian.master/config/amd64/config.common.amd64 /home/source/debian.master/config/amd64/config.flavour.generic | sed -e 's/.*CONFIG_VERSION_SIGNATURE.*/CONFIG_VERSION_SIGNATURE="Ubuntu 5.18.15-051815.202207300418-generic 5.18.15"/' > /home/source/debian/build/build-generic/.config
[ "true" = 'true' ] && true || \
        sed -ie 's/.*CONFIG_UBUNTU_ODM_DRIVERS.*/# CONFIG_UBUNTU_ODM_DRIVERS is not set/' \
            /home/source/debian/build/build-generic/.config
find /home/source/debian/build/build-generic -name "*.ko" | xargs rm -f
make ARCH=x86 CROSS_COMPILE=x86_64-linux-gnu- HOSTCC=x86_64-linux-gnu-gcc-11 CC=x86_64-linux-gnu-gcc-11 KERNELVERSION=5.18.15-051815-generic CONFIG_DEBUG_SECTION_MISMATCH=y KBUILD_BUILD_VERSION="202207300418" LOCALVERSION= localver-extra= CFLAGS_MODULE="-DPKG_ABI=051815" PYTHON=python3 O=/home/source/debian/build/build-generic -j1 syncconfig prepare scripts
make[1]: Entering directory '/home/source'
make[2]: Entering directory '/home/source/debian/build/build-generic'
  GEN     Makefile
  HOSTCC  scripts/basic/fixdep
/bin/sh: 1: x86_64-linux-gnu-gcc-11: not found
make[4]: *** [/home/source/scripts/Makefile.host:95: scripts/basic/fixdep] Error 127
make[3]: *** [/home/source/Makefile:564: scripts_basic] Error 2
make[2]: *** [/home/source/Makefile:350: __build_one_by_one] Error 2
make[2]: Leaving directory '/home/source/debian/build/build-generic'
make[1]: *** [Makefile:219: __sub-make] Error 2
make[1]: Leaving directory '/home/source'
make: *** [debian/rules.d/2-binary-arch.mk:31: /home/source/debian/stamps/stamp-prepare-tree-generic] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
********

Building meta package

********
********

Moving packages to debs folder

********
mv: cannot stat '/home/source/../*.*': No such file or directory

**Comment by TuxInvader** [comment]
It looks like the Ubuntu mainline team changed the build to require gcc-11, which isn't available in focal.
All we can do is modify the build scripts to default back to version 9.

**Comment by TuxInvader** [comment]
This should be fixed in b8388d7b6430156b3c7bb19eecad51741b663e6b
Try pulling the `latest` or `v1.5` image from dockerhub :-)
