### ISSUE TITLE
these 5.10.x kernels discontinued?

### ISSUE THREAD

**Issue by ghost** [TuxInvader/focal-mainline-builder#25]
Last from a month ago (5.10.128) and latest came out today (5.10.135)?

Are these 5.10.x kernel build discontinued or they will be back?

If no, how I will change to 5.18, 5.19 builds on my 20.04?

**Comment by muzena** [comment]
You must install them manually.
https://launchpad.net/~trebelnik-stefina/+archive/ubuntu/kernel/+packages

**Comment by TuxInvader** [comment]
Hi @runboy93 - the longterm kernel has been updated now. Cheers ;-)

**Comment by TuxInvader** [comment]
@runboy93 - the latest longterm kernel is 5.15.x. I would suggest that you `apt install linux-generic-5.15` if you intend to stick with the longterm kernels. Alternatively you can switch to the bleeding edge by using the other repo.
