### ISSUE TITLE
Can't compile with the last kernel releases (6.0.10,11 &6.1) - unsupported operand type(s) for |=: 'dict' and 'dict'

### ISSUE THREAD

**Issue by myna-me** [TuxInvader/focal-mainline-builder#32]
Just wondering if anyone else is getting the same errors I am getting:
check-config: loading annotations from /home/source/debian.master/config/annotations

```
Traceback (most recent call last):
  File "/home/source/debian/scripts/misc/kconfig/annotations.py", line 79, in _parse_body
    entry['policy'] |= literal_eval(m.group(1))
TypeError: unsupported operand type(s) for |=: 'dict' and 'dict'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "debian/scripts/misc/annotations", line 248, in <module>
    main()
  File "debian/scripts/misc/annotations", line 239, in main
    do_check(args)
  File "debian/scripts/misc/annotations", line 178, in do_check
    a = Annotation(args.file)
  File "/home/source/debian/scripts/misc/kconfig/annotations.py", line 20, in __init__
    self._parse(raw_data)
  File "/home/source/debian/scripts/misc/kconfig/annotations.py", line 120, in _parse
    self._parse_body(data)
  File "/home/source/debian/scripts/misc/kconfig/annotations.py", line 88, in _parse_body
    raise Exception(str(e) + f', line = {line}')
Exception: unsupported operand type(s) for |=: 'dict' and 'dict', line = CONFIG_104_QUAD_8 policy<{'amd64': 'm'}>
make: *** [debian/rules.d/4-checks.mk:32: config-prepare-check-generic] Error 1
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
```
@TuxInvader , i noticed that in your PPA, you had uploaded 6.0.10 and 11...i think. So you are being able to compile without issue?

**Comment by TuxInvader** [comment]
These started failing upstream a while back. See: https://kernel.ubuntu.com/~kernel-ppa/mainline/v6.1/amd64/log
My kernels are also broken, I upload the source packages to launchpad and they get built in "the cloud". I've not successfully published a kernel package since 6.0.9.

**Comment by myna-me** [comment]
maaaaan. this is sad. well, thanks for letting me know that it isn't something i had done wrong.
I'll close this "issue" , but hopefully this will assist anyone searching, so that they know that it isn't this docker but just a larger (and depressing) issue. ;)

**Comment by Augusto7743** [comment]
Accessing
https://kernel.ubuntu.com/~kernel-ppa/mainline/v6.1/amd64/
not any kernel compiled deb files.

Perhaps not more kernel updates to Focal 20.04 ?
