### ISSUE TITLE
Can't install 6.x kernel packages on jammy

### ISSUE THREAD

**Issue by masemoel** [TuxInvader/focal-mainline-builder#35]
I don't know why but I can't install 6.0 or 6.1 kernels on Jammy since some weeks. I saw on launchpad that you were getting errors with amd64, but now I see you have been able to build succesfully though I still get these errors:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 linux-generic-6.00 : Depends: linux-headers-6.0.18-060018-generic but it is not instalable
                      Depends: linux-image-unsigned-6.0.18-060018-generic but it is not instalable
                      Depends: linux-modules-6.0.18-060018-generic but it is not instalable
E: Unable to correct problems, you have held broken packages.
```
Same happens with linux-generic.6.01 package.

**Comment by Theelx** [comment]
Can confirm, that happens with me too.

**Comment by masemoel** [comment]
> Can confirm, that happens with me too.

I have been able to install right now the linux-generic-6.01 package. Are you trying the same package?

**Comment by Theelx** [comment]
Oh, I just saw that new packages were uploaded 8-9 hours ago. I tested yesterday and it didn't work, however maybe the new ones will.

**Comment by Theelx** [comment]
Ok, just tested again and it works! Thanks so much!

**Comment by masemoel** [comment]
I will close this now :) I retried today since I saw recent activity at https://launchpad.net/~tuxinvader/+archive/ubuntu/jammy-mainline with succesful builds.
