### ISSUE TITLE
Incorrect Header Packages

### ISSUE THREAD

**Issue by sepatel** [TuxInvader/focal-mainline-builder#5]
Looks like the headers (the one without the -generic) do not include any of the actual source header fiels in them. Thus all of the symlinks from the -generic header are breaking. As a temporary work around I could download the original kernel-ppa and install the _all .deb file and then do the following symlink

`sudo ln -s /usr/src/linux-headers-5.12.7-051207 /usr/src/linux-5.12.7-headers-5.12.7-051207`

To make it work but the one included in your package is missing the header files completely (only looked at the .6 and .7 releases so I figure it has been a problem for a longer) and also the naming pattern that the symlinks are looking for is inaccurate as well so in addition to using the original .deb packages just to get the source code, you also have to create a symlink to have your version of the -generic symlink to the correct headers as well.

Just to add why this is important, you cannot build the nvidia binaries or anything else that requires kernel source code (thus anything from the dkms) without making this correction by hand after installing from your lts ppa (which I also assume is temporary until the actual kernel-ppa fixes their junk and goes back to the 5.31 instead of 5.33 glib)

**Comment by TuxInvader** [comment]
Hi @sepatel,

Thanks for raising this issue. I don't use any out of kernel drivers and hadn't noticed this was broken. It should be fixed now, and I'm submitting updates packages to the PPAs for 5.12.7, 5.11.22 and 5.10.40.

Cheers

**Comment by sepatel** [comment]
I validated with the 5.12.8 kernel and it works great. Thank you very much. Your efforts to maintain this are an amazing help.

**Comment by PaulRehel** [comment]
dpkg: dependency problems prevent configuration of linux-headers-5.12.8-051208-generic:
 linux-headers-5.12.8-051208-generic depends on libc6 (>= 2.33); however:
  Version of libc6:amd64 on system is 2.27-3ubuntu1.4.

dpkg: error processing package linux-headers-5.12.8-051208-generic (--install):
 dependency problems - leaving unconfigured

Processing triggers for linux-image-unsigned-5.12.8-051208-generic (5.12.8-051208.202105281232) ...
/etc/kernel/postinst.d/dkms:
 * dkms: running auto installation service for kernel 5.12.8-051208-generic

Kernel preparation unnecessary for this kernel.  Skipping...
applying patch disable_fstack-clash-protection_fcf-protection.patch...patching file Kbuild
Hunk #1 succeeded at 82 (offset 11 lines).

unset ARCH; [ ! -h /usr/bin/cc ] && export CC=/usr/bin/gcc; env NV_VERBOSE=1 'make' -j8 NV_EXCLUDE_BUILD_MODULES='' KERNEL_UNAME=5.12.8-051208-generic IGNORE_XEN_PRESENCE=1 IGNORE_CC_MISMATCH=1 SYSSRC=/lib/modules/5.12.8-051208-generic/build LD=/usr/bin/ld.bfd modules......(bad exit status: 2)
ERROR (dkms apport): kernel package linux-headers-5.12.8-051208-generic is not supported
Error! Bad return status for module build on kernel: 5.12.8-051208-generic (x86_64)

**Comment by PaulRehel** [comment]
I finally got it work.  Went from 5.11.16 to 5.12.8.  Thank You
