### ISSUE TITLE
Build fails late while generating manpages

### ISSUE THREAD

**Issue by kronthto** [TuxInvader/focal-mainline-builder#8]
I'm trying to compile 5.10.46 and keep running into issues at the end when generating man pages. 
After 1h+ I first got an issue with missing `rst2man` for tools/bpf/bpftool/Documentation/Makefile.
I "fixed" this by adding `apt-get install python-docutils` to your image.
But after another 1h+ attempt I get a similar issue now with `asciidoc` for `tools/perf`.

I'm not sure why I get these issues now, the last time with 5.10.39 it worked just fine. I don't see changes to the Makefiles of these tools.

It is very frustrating that all the time to compile the kernel is lost and the process needs to be started from the beginning again each attempt / after installing a dependency, and I don't know what else I will need.

Do you have any idea / am I doing something wrong?

```
install -m755 debian/tools/generic /home/source/debian/linux-tools-common/usr/sbin/bpftool
make -C /home/source/debian/build/tools/tools/bpf/bpftool doc
make[1]: Entering directory '/home/source/debian/build/tools/tools/bpf/bpftool'
  DESCEND  Documentation
make[2]: Entering directory '/home/source/debian/build/tools/tools/bpf/bpftool/Documentation'
Makefile:45: *** "rst2man not found, but required to generate man pages".  Stop.
make[2]: Leaving directory '/home/source/debian/build/tools/tools/bpf/bpftool/Documentation'
make[1]: *** [Makefile:205: doc] Error 2
make[1]: Leaving directory '/home/source/debian/build/tools/tools/bpf/bpftool'
make: *** [debian/rules.d/3-binary-indep.mk:114: install-tools] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
********

Moving packages to debs folder

********
mv: cannot stat '/home/source/../*.*': No such file or directory
```

```
Makefile:215: Please install asciidoc to have the man pages installed
  ASCIIDOC perf-diff.xml
/bin/sh: 2: asciidoc: not found
make[4]: *** [Makefile:296: perf-diff.xml] Error 127
make[3]: *** [Makefile.perf:864: man] Error 2
make[2]: *** [Makefile.perf:229: sub-make] Error 2
make[1]: *** [Makefile:110: man] Error 2
make[1]: Leaving directory '/home/source/debian/build/tools/tools/perf'
make: *** [debian/rules.d/3-binary-indep.mk:119: install-tools] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
```

**Comment by TuxInvader** [comment]
It's strange that 5.10.46 is trying to build the tools? Did you enter a shell and modify `debian/rules` manually to include them?
I looked at the requirements for building the tools for issue #6 but they add 1G of build dependencies. I'll think about how I might be able to add them to the build with an option or create a separate a container that just compiles the tools.

If you want to build your own container then you need to include these packages:

```
apt-get install -y --no-install-recommends \
    asciidoc asciidoc-base asciidoc-common debhelper default-jdk-headless dh-autoreconf \
    dh-strip-nondeterminism dh-systemd docbook-utils docutils-common dvipng dwz fig2dev \
    fonts-font-awesome graphviz imagemagick imagemagick-6-common imagemagick-6.q16 kernel-wedge \
    latexmk libann0 libaudit-dev libcap-dev libcap-ng-dev libcdt5 libcgraph6 libdebhelper-perl \
    libdw-dev libelf-dev libfile-stripnondeterminism-perl libgts-0.7-5 libgvc6 libgvpr2 libjs-modernizr \
    libjs-sphinxdoc libjs-underscore liblab-gamut1 liblqr-1-0 liblzma-dev libmagickcore-6.q16-6 \
    libmagickwand-6.q16-6 libnetpbm10 libnewt-dev libnuma-dev libpathplan4 libpci-dev libpng-dev \
    librsvg2-bin libsgmls-perl libslang2-dev libsub-override-perl libtool libunwind-dev makedumpfile \
    netpbm openjdk-11-jdk-headless po-debconf python-babel-localedata python3-alabaster python3-babel \
    python3-docutils python3-imagesize python3-jinja2 python3-roman python3-sphinx zlib1g-dev \
    python3-sphinx-rtd-theme sgmlspl sphinx-common sphinx-rtd-theme-common uuid-dev xmlto xsltproc
```

If you add those to the Dockerfile, then you should have everything you need to compile the tools.

**Comment by kronthto** [comment]
Thanks for the list of deps!

No I did not modify anything.

It gets weirder, after I tried again with asciidoc I got:

```
# Add the tools.
install -d /home/source/debian/linux-tools-5.11.0-20/usr/lib
install -d /home/source/debian/linux-tools-5.11.0-20/usr/lib/linux-tools-5.11.0-20
install -m755 /home/source/debian/build/tools-perarch/tools/usb/usbip/bin/sbin/usbip \
	/home/source/debian/linux-tools-5.11.0-20/usr/lib/linux-tools-5.11.0-20
install -m755 /home/source/debian/build/tools-perarch/tools/usb/usbip/bin/sbin/usbipd \
	/home/source/debian/linux-tools-5.11.0-20/usr/lib/linux-tools-5.11.0-20
install -m755 /home/source/debian/build/tools-perarch/tools/power/acpi/acpidbg \
	/home/source/debian/linux-tools-5.11.0-20/usr/lib/linux-tools-5.11.0-20
install -m755 /home/source/debian/build/tools-perarch/tools/power/cpupower/cpupower \
	/home/source/debian/linux-tools-5.11.0-20/usr/lib/linux-tools-5.11.0-20
# Install only the full versioned libcpupower.so.5.11.0-20, not
# the usual symlinks to it.
install -m644 /home/source/debian/build/tools-perarch/tools/power/cpupower/libcpupower.so.5.11.0-20 \
	/home/source/debian/linux-tools-5.11.0-20/usr/lib/
install -m755 /home/source/debian/build/tools-perarch/tools/perf/perf /home/source/debian/linux-tools-5.11.0-20/usr/lib/linux-tools-5.11.0-20
install -m755 /home/source/debian/build/tools-perarch/tools/perf/libperf-jvmti.so /home/source/debian/linux-tools-5.11.0-20/usr/lib/linux-tools-5.11.0-20
install: cannot stat '/home/source/debian/build/tools-perarch/tools/perf/libperf-jvmti.so': No such file or directory
make: *** [debian/rules.d/2-binary-arch.mk:738: install-perarch] Error 1
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
```

Somehow 5.11 shows up (while building 5.10.46). I think maybe something is very wrong again caused by Canonicals packaging, we've seen the 5.11 packages show up on kernel.ubuntu.org for 5.10 releases too. Maybe this also causes this issue. I'm still investigating.

**Comment by TuxInvader** [comment]
That's very strange. I just built a 5.10.46 using:
```
docker run -ti -e kver=v5.10.46 -v /usr/local/src/cod/mainline:/home/source -v /usr/local/src/cod/debs:/home/debs --rm tuxinvader/focal-mainline-builder:latest --btype=binary --exclude=udebs --flavour=generic
```
And it all worked fine. If I check the git status I have:
```
$ git status
HEAD detached at cod/mainline/v5.10.46
nothing to commit, working tree clean
```
what arguments did you provide to the container?

**Comment by kronthto** [comment]
Normally only the `checkbugs=yes` flag - everything else default. 
I saw that starting with 5.10.44 they do include the debian.master-21.10 directory **so I set it to false...**

But looking into the changelog of that I see 5.11.0 stuff all over the place: https://git.launchpad.net/~ubuntu-kernel-test/ubuntu/+source/linux/+git/mainline-crack/tree/debian.master-21.10/changelog?h=cod/mainline/v5.10.46

I'm currently trying again with the flag (so not using that 5.11 config dir, the debian.master$ looks fine), and also manually wiped the workingtree of any possible previous build artifacts.

**Comment by TuxInvader** [comment]
I made `checkbugs` default to `yes` a while back, when It became impossible to build a kernel (5.12.x at least) on launchpad because they removed the LZ4 dependency from the debian control file, but still used it in the kernel?!?!?

You definitely need that `checkbugs` enabled, precisely because they added that spurious `debian.master-21.10` folder

**Comment by kronthto** [comment]
Sorry then this was my fault getting baited by the added existence of that 21.10 thing. I thought maybe they "fixed" something but yeah .. :D
