### ISSUE TITLE
Kernel 5.13

### ISSUE THREAD

**Issue by WMAL** [TuxInvader/focal-mainline-builder#9]
Thank you for your work can you please upload kernel headers for 5.13

Apparently 5.13 has same dependency problem of libc6 2.33

**Comment by TuxInvader** [comment]
Hi,

The 5.13 kernel is now on my `lts-mainline` ppa along with the headers. There should be no libc2.33 dependency as they are all built for focal (20.04-LTS).

```
$ dpkg -I /var/cache/apt/archives/linux-headers-5.13-051300-generic_5.13-051300.202106282201_amd64.deb 
<--snip-->
 Depends: linux-headers-5.13-051300, libc6 (>= 2.22), libelf1 (>= 0.142), libssl1.1 (>= 1.1.0), zlib1g (>= 1:1.2.3.3)
<--snip-->
```

**Comment by WMAL** [comment]
Testes 5.13 works perfectly thank you  

May I ask which config are you using to compile the kernels is it  Ubuntu focal or something else

**Comment by TuxInvader** [comment]
They are built using the mainline configs from Ubuntu. The 5.13 configuration will be taken from here:

https://git.launchpad.net/~ubuntu-kernel-test/ubuntu/+source/linux/+git/mainline-crack/tree/debian.master/config?h=cod/mainline/v5.13

Cheers

**Comment by WMAL** [comment]
Excellent thank you

**Comment by WMAL** [comment]
5.13.1 has been released thank you
